### ISSUE TITLE
Questions about decryption process

### ISSUE THREAD

**Issue by jesse77169** [secworks/cbc#2]
When I use CBC mode to decrypt, I can't get the desired result, so I need your help
My process is like this：
1.  address    8'h10-8'h17      write 256 bit key   ，from the outside to the inside of the cbc.v
2.  address 8'h20-8'h23       write   block 
3. address   8'40  -8'h43      write  iv    
4. address   8'h0a                write   32'b10
5. address  8'h08            write   32'b11 ,      we<= 1'b0
6.   address  8'h09      if (tmp_read_data[1:0] == 2'b11)      Get results when conditions are met
What's wrong with my method? I look forward to your reply

**Comment by secworks** [comment]
Hi!
Not sure what you mean at (5) with ", we <= 1'b0".
But judging from the list of steps, I don't see that you initialize the cipher.
After setting the key in (1) you need to write to write a one to CTRL_INIT_BIT (address 8'h08) to initalize the AES engine. Then you can perform encryption operations. You can't perform init() and next() at the same time. (The AES engine will not have correct round keys.)

I suggest looking at the example, test code in https://github.com/secworks/cbc/blob/master/src/tb/tb_cbc.v
If this doesn't solve your problem, check endianess. That is often the problem.

I will add a task clarifying the init() and next() behaviour.

**Comment by jesse77169** [comment]
Hi
I noticed that your word is "encryption operations"
If I need to use "aes_decipher_block", is this the same process？

**Comment by secworks** [comment]
Yes, the AES core includes both encipher and decipher functionality. You set the encdec bit in the config register (0x0a) for encryption operations, or clear the bit for decryption. Again, I suggest looking at the test code. It performs both encryption and decryption.
